worker_processes auto;
worker_rlimit_nofile 65535;

events {
    worker_connections 8192;
    multi_accept on;
    use epoll;
}

# --- 1. JALUR PROXY STREAM (LOW LATENCY & CEPAT BERSIH) ---
stream {
    resolver 1.1.1.1 1.0.0.1 8.8.8.8 valid=300s ipv6=off;
    resolver_timeout 2s;

    # Matikan log untuk membuang beban disk I/O
    access_log off;
    error_log /dev/null crit;

    # Buffer & Timeout Gesit
    proxy_buffer_size 128k;
    proxy_connect_timeout 2s;
    proxy_timeout 5m; # 5 menit: socket zombie/scan langsung diputus otomatis

    server {
        listen 8080 reuseport backlog=4096;
        ssl_preread on;
        proxy_pass $ssl_preread_server_name:443;

        # Bypass delay paket TCP
        tcp_nodelay on;
        proxy_socket_keepalive on;
    }
}

# --- 2. JALUR MONITOR UI RINGAN ---
http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log off;
    error_log /dev/null crit;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /nginx_status {
            stub_status;
            access_log off;
        }
    }
}
