worker_processes auto;
worker_rlimit_nofile 1048576;

events {
    worker_connections 65535;
    multi_accept on;
    use epoll;
}

# --- 1. JALUR STREAM PROXY (SUPER CEPAT) ---
stream {
    # DNS Caching panjang agar tidak lag di awal buka web
    resolver 1.1.1.1 1.0.0.1 8.8.8.8 valid=3600s ipv6=off;
    resolver_timeout 2s;

    # Format log ringkas
    log_format stream_monitor '$remote_addr [$time_local] '
                              'Target: $ssl_preread_server_name '
                              'Bytes: [RX: $bytes_received | TX: $bytes_sent] '
                              'Duration: ${session_time}s '
                              'Status: $status';

    # Buffer log diperbesar ke 64k agar Nginx tidak tersendat menulis disk
    access_log /var/log/nginx/stream.log stream_monitor buffer=64k flush=10s;
    error_log /dev/null crit;

    # Buffer data dinaikkan agar download kencang
    proxy_buffer_size 128k;
    proxy_connect_timeout 3s;
    proxy_timeout 15m; # 15 menit cukup agar socket mati otomatis dibersihkan

    server {
        listen 8080 reuseport backlog=65535;
        ssl_preread on;
        proxy_pass $ssl_preread_server_name:443;
        
        # Matikan delay socket seketika
        tcp_nodelay on;
        proxy_socket_keepalive on;
    }
}

# --- 2. JALUR DASHBOARD ---
http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /nginx_status {
            stub_status;
            access_log off;
        }

        location /api/logs {
            default_type text/plain;
            alias /var/log/nginx/stream.log;
            access_log off;
        }
    }
}
